// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjPMF9oYhR8yPlG9WM7ZxCEI2VL1nBz9A',
    appId: '1:450326154861:web:298405d6b87caad24b3964',
    messagingSenderId: '450326154861',
    projectId: 'fil-lan-f60bc',
    authDomain: 'fil-lan-f60bc.firebaseapp.com',
    databaseURL: 'https://fil-lan-f60bc-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fil-lan-f60bc.appspot.com',
    measurementId: 'G-T13MV0PWKN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3Xqb19jULhfT8Nw2-nLqTBMV4buoCUO8',
    appId: '1:450326154861:android:401e7d5cc762b6084b3964',
    messagingSenderId: '450326154861',
    projectId: 'fil-lan-f60bc',
    databaseURL: 'https://fil-lan-f60bc-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fil-lan-f60bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrgYaikOmlxnB8C_UQDbPpT09P2WCYSjI',
    appId: '1:450326154861:ios:dc38f984e46f83784b3964',
    messagingSenderId: '450326154861',
    projectId: 'fil-lan-f60bc',
    databaseURL: 'https://fil-lan-f60bc-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fil-lan-f60bc.appspot.com',
    iosClientId: '450326154861-qb0o7vi6nd3hdnidl67ne8ur0vdlu26l.apps.googleusercontent.com',
    iosBundleId: 'com.example.filLan',
  );
}
